name: release

on:
  pull_request:
  push:
    branches:    
      - 'master'
    tags: 
       - '*'

jobs:
  staging-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to ECR
        id: ecr
        uses: elgohr/ecr-login-action@1.0.1
        with:
          access_key: ${{ secrets.AWS_STAGING_ACCESS_KEY }}
          secret_access_key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
      - name: Build image and publish it to staging registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: 521664337176.dkr.ecr.us-east-1.amazonaws.com/application
          username: ${{ steps.ecr.outputs.username }}
          password: ${{ steps.ecr.outputs.password }}
          registry: ${{ steps.ecr.outputs.registry }}
          snapshot: true
          dockerfile: Dockerfile
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
